// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by Flutist

import 'package:flutist/flutist.dart';

/// Extension for package.dependencies.xxx access
extension PackageDependenciesX on List<Dependency> {
  /// Dependency getter for http
  Dependency get http => firstWhere((d) => d.name == 'http');

  /// Dependency getter for test
  Dependency get test => firstWhere((d) => d.name == 'test');

  /// Dependency getter for mockito
  Dependency get mockito => firstWhere((d) => d.name == 'mockito');
}

/// Extension for package.modules.xxx access
extension PackageModulesX on List<Module> {
  /// Module getter for app
  Module get app => firstWhere((m) => m.name == 'app');

  /// Module getter for auth_domain
  Module get authDomain => firstWhere((m) => m.name == 'auth_domain');

  /// Module getter for auth_data
  Module get authData => firstWhere((m) => m.name == 'auth_data');

  /// Module getter for auth_presentation
  Module get authPresentation =>
      firstWhere((m) => m.name == 'auth_presentation');

  /// Module getter for network_interface
  Module get networkInterface =>
      firstWhere((m) => m.name == 'network_interface');

  /// Module getter for network_implementation
  Module get networkImplementation =>
      firstWhere((m) => m.name == 'network_implementation');

  /// Module getter for network_testing
  Module get networkTesting =>
      firstWhere((m) => m.name == 'network_testing');

  /// Module getter for network_tests
  Module get networkTests => firstWhere((m) => m.name == 'network_tests');

  /// Module getter for utils
  Module get utils => firstWhere((m) => m.name == 'utils');
}
